### PR TITLE
Render database ER diagrams with FloorPlan

### PR DESCRIPTION
**Pull request by julioz**
[FloorPlan](https://github.com/julioz/FloorPlan) translates database schemas into entity-relationship diagrams, to make it easier to inspect changes in the persistance-layer schema of the app.

Here, I am configuring FloorPlan to output `SVG` files by mimicking the SQLDelight directory structure, into a sibling directory under the `:common` module. 

The first commit is the SQLDelight plugin configuration to export database schemas into a `.db` file, which is then checked-in. Lastly, we set up FloorPlan to read from the exported DB schemas and render an SVG diagram for the given database.

You can export SQLDelight's schemas by using the [`generateSchema`](https://github.com/cashapp/sqldelight/blob/master/sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateSchemaTask.kt) gradle task:
```
./gradlew generateAndroidDebugPeopleInSpaceDatabaseSchema
```

And then manually generate the ER diagrams by running

```
./gradlew generateFloorPlan
```

Optionally, we could also make `compileDebugJava`/`kaptDebugKotlin` depend on `generateFloorPlan`, and we would get automatic diagram generation on builds for that module, similarly to how [Room hooks into the build process to generate the JSON schemas](https://stackoverflow.com/a/57103344/12511149).
Let me know your thoughts on this.

### CODE REVIEW

**Comment by joreilly** [comment]
Looks good, thanks!

**Comment by joreilly** [comment]
@julioz github actions based build failed after I merged this......see same locally if I run `./gradlew assembleDebug`

```
Execution failed for task ':common:packageDebugResources'.
> org/apache/batik/w3c/dom/ElementTraversal
```

**Comment by joreilly** [comment]
seems to be triggered by inclusion of `classpath("com.juliozynger.floorplan:floorplan-gradle-plugin:${Versions.floorPlan}")`  in main `build.gradle.kts`

**Comment by julioz** [comment]
@joreilly Oh, interesting. Let me take a look and will get back to you very soon.

**Pull request merged**
