### PR TITLE
trying out compose for iOS experimental support

### PR DESCRIPTION
**Pull request by joreilly**

### CODE REVIEW

**Comment by shubhamsinghmutualmobile** [comment]
Hi @joreilly 
First of all, thanks for this great project. Got so much to learn from it.
Now secondly, regarding Compose for iOS, I've been trying to run the project on the main branch but the project's failing on me saying:

```
* What went wrong:
Execution failed for task ':compose-ios:iosSimulatorBuildIPhone8Debug'.
> External tool execution failed:
  * Command: [/usr/bin/xcrun, xcodebuild, -scheme, PeopleInSpace, -project, ., -configuration, Debug, -derivedDataPath, build, -arch, x86_64, -sdk, iphonesimulator15.2]
  * Working dir: [/Users/shubhamsingh/StudioProjects/PeopleInSpace/compose-ios/build/ios/IPhone8/PeopleInSpace.xcodeproj]
  * Exit code: 65
  * Standard output log: /Users/shubhamsingh/StudioProjects/PeopleInSpace/compose-ios/build/compose/logs/iosSimulatorBuildIPhone8Debug/xcrun-2022-05-04-10-13-19-out.txt
  * Error log: /Users/shubhamsingh/StudioProjects/PeopleInSpace/compose-ios/build/compose/logs/iosSimulatorBuildIPhone8Debug/xcrun-2022-05-04-10-13-19-err.txt

```

and inside the above mentioned file, the error it shows is this:
```
The following build commands failed:
	PhaseScriptExecution GradleCompile /Users/shubhamsingh/StudioProjects/PeopleInSpace/compose-ios/build/ios/IPhone8/PeopleInSpace.xcodeproj/build/Build/Intermediates.noindex/PeopleInSpace.build/Debug-iphonesimulator/PeopleInSpace.build/Script-CCAD86B04FEA11721FB108A8.sh (in target 'PeopleInSpace' from project 'PeopleInSpace')
(1 failure)
```


My system details are:
```
Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.ankit.mahadik.json.dart.class (2.13), com.herbert.george.flutter-snippets (2.0.0-stable-1), dev.polek.adbwifi (1.2.4), in.xiv.cs (0.1), com.genuitec.codetogether (2022.1.4-01289), Dart (211.7811), com.ixigua.flutter_asset_iteral (1.7.6), com.localizely.flutter-intl (1.17.2-2020.3), wu.seal.tool.jsontokotlin (3.7.2), org.jetbrains.kotlin (211-1.6.20-release-275-AS7442.40), io.flutter (66.0.1), com.jetbrains.kmm (0.3.2(211-1.6.10-release-974-IJ)-91), com.nbadal.ktlint (0.9.0), com.suusan2go.kotlin-fill-class (1.0.11), gherkin (211.6693.111), org.intellij.plugins.markdown (211.7142.37), com.squareup.sqldelight (1.5.1)
```

By any chance, would you happen to have an idea as to how to fix this?

**Comment by joreilly** [comment]
Hmm, not sure....fwiw I've been running `iosDeployIPhone8Debug` gradle task here. Can you try that?  (I must updated `README` as well to mention that).

**Comment by shubhamsinghmutualmobile** [comment]
Yes I've been getting this error from running that only.. you have mentioned that in the gradle.kts file i.e. `Usage: ./gradlew iosDeployIPhone8Debug`

But when I try to run the `compose-ios[uikitX64]` task from the default configurations, it shows me this error:
```
Module "org.jetbrains.compose.runtime:runtime-saveable (org.jetbrains.compose.runtime:runtime-saveable-uikitx64)" has a reference to symbol androidx.compose.runtime/remember|-2215966373931868872[0]. Neither the module itself nor its dependencies contain such declaration.

This could happen if the required dependency is missing in the project. Or if there is a dependency of "org.jetbrains.compose.runtime:runtime-saveable (org.jetbrains.compose.runtime:runtime-saveable-uikitx64)" that has a different version in the project than the version that "org.jetbrains.compose.runtime:runtime-saveable (org.jetbrains.compose.runtime:runtime-saveable-uikitx64): 0.0.0-master-dev673" was initially compiled with. Please check that the project configuration is correct and has consistent versions of all required dependencies.

The list of "org.jetbrains.compose.runtime:runtime-saveable (org.jetbrains.compose.runtime:runtime-saveable-uikitx64): 0.0.0-master-dev673" dependencies that may lead to conflicts:
1. "stdlib: 1.6.20" (was initially compiled with "stdlib: 1.6.21")
2. "org.jetbrains.kotlin.native.platform.CoreFoundation: 1.6.20" (was initially compiled with "org.jetbrains.kotlin.native.platform.CoreFoundation: 1.6.21")
3. "org.jetbrains.kotlin.native.platform.darwin: 1.6.20" (was initially compiled with "org.jetbrains.kotlin.native.platform.darwin: 1.6.21")
4. "org.jetbrains.kotlin.native.platform.posix: 1.6.20" (was initially compiled with "org.jetbrains.kotlin.native.platform.posix: 1.6.21")
5. "org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.2" (was initially compiled with "org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64)")
6. "org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.1" (was initially compiled with "org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64)")

Project dependencies:
+--- co.touchlab:kermit (co.touchlab:kermit-iosx64): 1.0.0
+--- com.rickclephas.kmp:kmp-nativecoroutines-annotations (com.rickclephas.kmp:kmp-nativecoroutines-annotations-iosx64): 0.12.1-new-mm
+--- com.rickclephas.kmp:kmp-nativecoroutines-core (com.rickclephas.kmp:kmp-nativecoroutines-core-iosx64): 0.12.1-new-mm
|    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.1
|         +--- stdlib: 1.6.0 -> 1.6.20
|         +--- org.jetbrains.kotlin.native.platform.CoreFoundation: 1.6.0 -> 1.6.20
|         |    +--- stdlib: 1.6.20
|         |    +--- org.jetbrains.kotlin.native.platform.darwin: 1.6.20
|         |    |    +--- stdlib: 1.6.20
|         |    |    \--- org.jetbrains.kotlin.native.platform.posix: 1.6.20
|         |    |         \--- stdlib: 1.6.20
|         |    \--- org.jetbrains.kotlin.native.platform.posix: 1.6.20 (*)
|         +--- org.jetbrains.kotlin.native.platform.darwin: 1.6.0 -> 1.6.20 (*)
|         +--- org.jetbrains.kotlin.native.platform.posix: 1.6.0 -> 1.6.20 (*)
|         +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.0 -> 0.17.2
|         |    +--- stdlib: 1.6.20
|         |    +--- org.jetbrains.kotlin.native.platform.posix: 1.6.20 (*)
|         |    \--- org.jetbrains.kotlinx:atomicfu-cinterop-interop: 0.17.2
|         |         +--- stdlib: 1.6.20
|         |         \--- org.jetbrains.kotlin.native.platform.posix: 1.6.20 (*)
|         \--- org.jetbrains.kotlinx:atomicfu-cinterop-interop: 0.17.2 (*)
+--- com.squareup.sqldelight:coroutines-extensions (com.squareup.sqldelight:coroutines-extensions-iosx64): 1.5.3
|    +--- com.squareup.sqldelight:runtime (com.squareup.sqldelight:runtime-iosx64): 1.5.3
|    |    +--- co.touchlab:stately-collections (co.touchlab:stately-collections-iosx64): 1.1.10
|    |    |    +--- co.touchlab:stately-common (co.touchlab:stately-common-iosx64): 1.1.10
|    |    |    \--- co.touchlab:stately-concurrency (co.touchlab:stately-concurrency-iosx64): 1.1.10
|    |    |         \--- co.touchlab:stately-common (co.touchlab:stately-common-iosx64): 1.1.10
|    |    \--- co.touchlab:stately-common (co.touchlab:stately-common-iosx64): 1.1.10
|    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.5.2-native-mt -> 1.6.1 (*)
+--- com.squareup.sqldelight:native-driver (com.squareup.sqldelight:native-driver-iosx64): 1.5.3
|    +--- co.touchlab:sqliter-driver (co.touchlab:sqliter-driver-iosx64): 1.0.10
|    +--- co.touchlab:stately-common (co.touchlab:stately-common-iosx64): 1.1.10
|    \--- com.squareup.sqldelight:runtime (com.squareup.sqldelight:runtime-iosx64): 1.5.3 (*)
+--- com.squareup.sqldelight:runtime (com.squareup.sqldelight:runtime-iosx64): 1.5.3 (*)
+--- io.insert-koin:koin-core (io.insert-koin:koin-core-iosx64): 3.1.6
+--- io.insert-koin:koin-test (io.insert-koin:koin-test-iosx64): 3.1.6
|    \--- io.insert-koin:koin-core (io.insert-koin:koin-core-iosx64): 3.1.6
+--- io.ktor:ktor-client-content-negotiation (io.ktor:ktor-client-content-negotiation-iosx64): 2.0.0
|    +--- io.ktor:ktor-client-core (io.ktor:ktor-client-core-iosx64): 2.0.0
|    |    +--- io.ktor:ktor-events (io.ktor:ktor-events-iosx64): 2.0.0
|    |    |    +--- io.ktor:ktor-http (io.ktor:ktor-http-iosx64): 2.0.0
|    |    |    |    +--- io.ktor:ktor-utils (io.ktor:ktor-utils-iosx64): 2.0.0
|    |    |    |    |    +--- io.ktor:ktor-io (io.ktor:ktor-io-iosx64): 2.0.0
|    |    |    |    |    |    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    |    |    |    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    |    |    |    |    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    |    |    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    |    |    |    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    |    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    |    |    +--- io.ktor:ktor-utils (io.ktor:ktor-utils-iosx64): 2.0.0 (*)
|    |    |    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    |    +--- io.ktor:ktor-http (io.ktor:ktor-http-iosx64): 2.0.0 (*)
|    |    +--- io.ktor:ktor-websocket-serialization (io.ktor:ktor-websocket-serialization-iosx64): 2.0.0
|    |    |    +--- io.ktor:ktor-http (io.ktor:ktor-http-iosx64): 2.0.0 (*)
|    |    |    +--- io.ktor:ktor-serialization (io.ktor:ktor-serialization-iosx64): 2.0.0
|    |    |    |    +--- io.ktor:ktor-http (io.ktor:ktor-http-iosx64): 2.0.0 (*)
|    |    |    |    +--- io.ktor:ktor-websockets (io.ktor:ktor-websockets-iosx64): 2.0.0
|    |    |    |    |    +--- io.ktor:ktor-http (io.ktor:ktor-http-iosx64): 2.0.0 (*)
|    |    |    |    |    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    |    |    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    |    |    |    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    |    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    |    |    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    |    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    +--- io.ktor:ktor-serialization (io.ktor:ktor-serialization-iosx64): 2.0.0 (*)
|    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
+--- io.ktor:ktor-client-core (io.ktor:ktor-client-core-iosx64): 2.0.0 (*)
+--- io.ktor:ktor-client-ios (io.ktor:ktor-client-ios-iosx64): 2.0.0
|    +--- io.ktor:ktor-client-darwin (io.ktor:ktor-client-darwin-iosx64): 2.0.0
|    |    +--- io.ktor:ktor-client-core (io.ktor:ktor-client-core-iosx64): 2.0.0 (*)
|    |    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
+--- io.ktor:ktor-client-json (io.ktor:ktor-client-json-iosx64): 2.0.0
|    +--- io.ktor:ktor-client-core (io.ktor:ktor-client-core-iosx64): 2.0.0 (*)
|    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
+--- io.ktor:ktor-client-logging (io.ktor:ktor-client-logging-iosx64): 2.0.0
|    +--- io.ktor:ktor-client-core (io.ktor:ktor-client-core-iosx64): 2.0.0 (*)
|    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
+--- io.ktor:ktor-serialization-kotlinx-json (io.ktor:ktor-serialization-kotlinx-json-iosx64): 2.0.0
|    +--- io.ktor:ktor-http (io.ktor:ktor-http-iosx64): 2.0.0 (*)
|    +--- io.ktor:ktor-serialization-kotlinx (io.ktor:ktor-serialization-kotlinx-iosx64): 2.0.0
|    |    +--- io.ktor:ktor-http (io.ktor:ktor-http-iosx64): 2.0.0 (*)
|    |    +--- io.ktor:ktor-serialization (io.ktor:ktor-serialization-iosx64): 2.0.0 (*)
|    |    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    |    +--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    |    \--- org.jetbrains.kotlinx:kotlinx-serialization-core (org.jetbrains.kotlinx:kotlinx-serialization-core-iosx64): 1.3.2
|    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.1 -> 0.17.2 (*)
|    +--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    \--- org.jetbrains.kotlinx:kotlinx-serialization-json (org.jetbrains.kotlinx:kotlinx-serialization-json-iosx64): 1.3.2
|         \--- org.jetbrains.kotlinx:kotlinx-serialization-core (org.jetbrains.kotlinx:kotlinx-serialization-core-iosx64): 1.3.2
+--- org.jetbrains.compose.foundation:foundation (org.jetbrains.compose.foundation:foundation-uikitx64): 0.0.0-master-dev673
|    +--- org.jetbrains.compose.animation:animation (org.jetbrains.compose.animation:animation-uikitx64): 0.0.0-master-dev673
|    |    +--- org.jetbrains.compose.animation:animation-core (org.jetbrains.compose.animation:animation-core-uikitx64): 0.0.0-master-dev673
|    |    |    +--- org.jetbrains.compose.runtime:runtime (org.jetbrains.compose.runtime:runtime-uikitx64): 0.0.0-master-dev673
|    |    |    |    +--- stdlib: 1.6.21 -> 1.6.20
|    |    |    |    +--- org.jetbrains.kotlin.native.platform.CoreFoundation: 1.6.21 -> 1.6.20 (*)
|    |    |    |    +--- org.jetbrains.kotlin.native.platform.darwin: 1.6.21 -> 1.6.20 (*)
|    |    |    |    +--- org.jetbrains.kotlin.native.platform.posix: 1.6.21 -> 1.6.20 (*)
|    |    |    |    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.2 (*)
|    |    |    |    +--- org.jetbrains.kotlinx:atomicfu-cinterop-interop: 0.17.2 (*)
|    |    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    |    |    +--- org.jetbrains.compose.ui:ui (org.jetbrains.compose.ui:ui-uikitx64): 0.0.0-master-dev673
|    |    |    |    +--- org.jetbrains.compose.runtime:runtime (org.jetbrains.compose.runtime:runtime-uikitx64): 0.0.0-master-dev673 (*)
|    |    |    |    +--- org.jetbrains.compose.runtime:runtime-saveable (org.jetbrains.compose.runtime:runtime-saveable-uikitx64): 0.0.0-master-dev673
|    |    |    |    |    ^^^ This module requires symbol androidx.compose.runtime/remember|-2215966373931868872[0].
|    |    |    |    |    +--- org.jetbrains.compose.runtime:runtime (org.jetbrains.compose.runtime:runtime-uikitx64): 0.0.0-master-dev673 (*)
|    |    |    |    |    +--- stdlib: 1.6.21 -> 1.6.20
|    |    |    |    |    +--- org.jetbrains.kotlin.native.platform.CoreFoundation: 1.6.21 -> 1.6.20 (*)
|    |    |    |    |    +--- org.jetbrains.kotlin.native.platform.darwin: 1.6.21 -> 1.6.20 (*)
|    |    |    |    |    +--- org.jetbrains.kotlin.native.platform.posix: 1.6.21 -> 1.6.20 (*)
|    |    |    |    |    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): unknown -> 0.17.2 (*)
|    |    |    |    |    +--- org.jetbrains.kotlinx:atomicfu-cinterop-interop: 0.17.2 (*)
|    |    |    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): unknown -> 1.6.1 (*)
|    |    |    |    +--- org.jetbrains.compose.ui:ui-geometry (org.jetbrains.compose.ui:ui-geometry-uikitx64): 0.0.0-master-dev673
|    |    |    |    |    +--- org.jetbrains.compose.runtime:runtime (org.jetbrains.compose.runtime:runtime-uikitx64): 0.0.0-master-dev673 (*)
|    |    |    |    |    \--- org.jetbrains.compose.ui:ui-util (org.jetbrains.compose.ui:ui-util-uikitx64): 0.0.0-master-dev673
|    |    |    |    +--- org.jetbrains.compose.ui:ui-graphics (org.jetbrains.compose.ui:ui-graphics-uikitx64): 0.0.0-master-dev673
|    |    |    |    |    +--- org.jetbrains.compose.runtime:runtime (org.jetbrains.compose.runtime:runtime-uikitx64): 0.0.0-master-dev673 (*)
|    |    |    |    |    +--- org.jetbrains.compose.ui:ui-unit (org.jetbrains.compose.ui:ui-unit-uikitx64): 0.0.0-master-dev673
|    |    |    |    |    |    +--- org.jetbrains.compose.runtime:runtime (org.jetbrains.compose.runtime:runtime-uikitx64): 0.0.0-master-dev673 (*)
|    |    |    |    |    |    +--- org.jetbrains.compose.ui:ui-geometry (org.jetbrains.compose.ui:ui-geometry-uikitx64): 0.0.0-master-dev673 (*)
|    |    |    |    |    |    \--- org.jetbrains.compose.ui:ui-util (org.jetbrains.compose.ui:ui-util-uikitx64): 0.0.0-master-dev673
|    |    |    |    |    +--- org.jetbrains.compose.ui:ui-util (org.jetbrains.compose.ui:ui-util-uikitx64): 0.0.0-master-dev673
|    |    |    |    |    \--- org.jetbrains.skiko:skiko (org.jetbrains.skiko:skiko-iosx64): 0.7.16
|    |    |    |    |         +--- org.jetbrains.kotlin:kotlin-stdlib: 1.6.10
|    |    |    |    |         |    \--- org.jetbrains:annotations: 13.0
|    |    |    |    |         \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.5.2 -> 1.6.1 (*)
|    |    |    |    +--- org.jetbrains.compose.ui:ui-text (org.jetbrains.compose.ui:ui-text-uikitx64): 0.0.0-master-dev673
|    |    |    |    |    +--- org.jetbrains.compose.runtime:runtime (org.jetbrains.compose.runtime:runtime-uikitx64): 0.0.0-master-dev673 (*)
|    |    |    |    |    +--- org.jetbrains.compose.runtime:runtime-saveable (org.jetbrains.compose.runtime:runtime-saveable-uikitx64): 0.0.0-master-dev673 (*)
|    |    |    |    |    |    ^^^ This module requires symbol androidx.compose.runtime/remember|-2215966373931868872[0].
|    |    |    |    |    +--- org.jetbrains.compose.ui:ui-graphics (org.jetbrains.compose.ui:ui-graphics-uikitx64): 0.0.0-master-dev673 (*)
|    |    |    |    |    +--- org.jetbrains.compose.ui:ui-unit (org.jetbrains.compose.ui:ui-unit-uikitx64): 0.0.0-master-dev673 (*)
|    |    |    |    |    +--- org.jetbrains.compose.ui:ui-util (org.jetbrains.compose.ui:ui-util-uikitx64): 0.0.0-master-dev673
|    |    |    |    |    +--- org.jetbrains.skiko:skiko (org.jetbrains.skiko:skiko-iosx64): 0.7.16 (*)
|    |    |    |    |    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.2 (*)
|    |    |    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    |    |    |    +--- org.jetbrains.compose.ui:ui-unit (org.jetbrains.compose.ui:ui-unit-uikitx64): 0.0.0-master-dev673 (*)
|    |    |    |    +--- org.jetbrains.compose.ui:ui-util (org.jetbrains.compose.ui:ui-util-uikitx64): 0.0.0-master-dev673
|    |    |    |    +--- org.jetbrains.skiko:skiko (org.jetbrains.skiko:skiko-iosx64): 0.7.16 (*)
|    |    |    |    +--- org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.2 (*)
|    |    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    |    |    +--- org.jetbrains.compose.ui:ui-unit (org.jetbrains.compose.ui:ui-unit-uikitx64): 0.0.0-master-dev673 (*)
|    |    |    +--- org.jetbrains.compose.ui:ui-util (org.jetbrains.compose.ui:ui-util-uikitx64): 0.0.0-master-dev673
|    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.0 -> 1.6.1 (*)
|    |    +--- org.jetbrains.compose.foundation:foundation-layout (org.jetbrains.compose.foundation:foundation-layout-uikitx64): 0.0.0-master-dev673
|    |    |    +--- org.jetbrains.compose.runtime:runtime (org.jetbrains.compose.runtime:runtime-uikitx64): 0.0.0-master-dev673 (*)
|    |    |    +--- org.jetbrains.compose.ui:ui (org.jetbrains.compose.ui:ui-uikitx64): 0.0.0-master-dev673 (*)
|    |    |    \--- org.jetbrains.compose.ui:ui-util (org.jetbrains.compose.ui:ui-util-uikitx64): 0.0.0-master-dev673
|    |    +--- org.jetbrains.compose.runtime:runtime (org.jetbrains.compose.runtime:runtime-uikitx64): 0.0.0-master-dev673 (*)
|    |    +--- org.jetbrains.compose.ui:ui (org.jetbrains.compose.ui:ui-uikitx64): 0.0.0-master-dev673 (*)
|    |    +--- org.jetbrains.compose.ui:ui-geometry (org.jetbrains.compose.ui:ui-geometry-uikitx64): 0.0.0-master-dev673 (*)
|    |    \--- org.jetbrains.compose.ui:ui-util (org.jetbrains.compose.ui:ui-util-uikitx64): 0.0.0-master-dev673
|    +--- org.jetbrains.compose.foundation:foundation-layout (org.jetbrains.compose.foundation:foundation-layout-uikitx64): 0.0.0-master-dev673 (*)
|    +--- org.jetbrains.compose.runtime:runtime (org.jetbrains.compose.runtime:runtime-uikitx64): 0.0.0-master-dev673 (*)
|    +--- org.jetbrains.compose.ui:ui (org.jetbrains.compose.ui:ui-uikitx64): 0.0.0-master-dev673 (*)
|    +--- org.jetbrains.compose.ui:ui-text (org.jetbrains.compose.ui:ui-text-uikitx64): 0.0.0-master-dev673 (*)
|    +--- org.jetbrains.compose.ui:ui-util (org.jetbrains.compose.ui:ui-util-uikitx64): 0.0.0-master-dev673
|    \--- org.jetbrains.skiko:skiko (org.jetbrains.skiko:skiko-iosx64): 0.7.16 (*)
+--- org.jetbrains.compose.material:material (org.jetbrains.compose.material:material-uikitx64): 0.0.0-master-dev673
|    +--- org.jetbrains.compose.animation:animation (org.jetbrains.compose.animation:animation-uikitx64): 0.0.0-master-dev673 (*)
|    +--- org.jetbrains.compose.animation:animation-core (org.jetbrains.compose.animation:animation-core-uikitx64): 0.0.0-master-dev673 (*)
|    +--- org.jetbrains.compose.foundation:foundation (org.jetbrains.compose.foundation:foundation-uikitx64): 0.0.0-master-dev673 (*)
|    +--- org.jetbrains.compose.foundation:foundation-layout (org.jetbrains.compose.foundation:foundation-layout-uikitx64): 0.0.0-master-dev673 (*)
|    +--- org.jetbrains.compose.material:material-icons-core (org.jetbrains.compose.material:material-icons-core-uikitx64): 0.0.0-master-dev673
|    |    \--- org.jetbrains.compose.ui:ui (org.jetbrains.compose.ui:ui-uikitx64): 0.0.0-master-dev673 (*)
|    +--- org.jetbrains.compose.material:material-ripple (org.jetbrains.compose.material:material-ripple-uikitx64): 0.0.0-master-dev673
|    |    +--- org.jetbrains.compose.animation:animation (org.jetbrains.compose.animation:animation-uikitx64): 0.0.0-master-dev673 (*)
|    |    +--- org.jetbrains.compose.foundation:foundation (org.jetbrains.compose.foundation:foundation-uikitx64): 0.0.0-master-dev673 (*)
|    |    +--- org.jetbrains.compose.runtime:runtime (org.jetbrains.compose.runtime:runtime-uikitx64): 0.0.0-master-dev673 (*)
|    |    \--- org.jetbrains.compose.ui:ui-util (org.jetbrains.compose.ui:ui-util-uikitx64): 0.0.0-master-dev673
|    +--- org.jetbrains.compose.runtime:runtime (org.jetbrains.compose.runtime:runtime-uikitx64): 0.0.0-master-dev673 (*)
|    +--- org.jetbrains.compose.ui:ui (org.jetbrains.compose.ui:ui-uikitx64): 0.0.0-master-dev673 (*)
|    +--- org.jetbrains.compose.ui:ui-text (org.jetbrains.compose.ui:ui-text-uikitx64): 0.0.0-master-dev673 (*)
|    \--- org.jetbrains.compose.ui:ui-util (org.jetbrains.compose.ui:ui-util-uikitx64): 0.0.0-master-dev673
+--- org.jetbrains.compose.runtime:runtime (org.jetbrains.compose.runtime:runtime-uikitx64): 0.0.0-master-dev673 (*)
+--- org.jetbrains.compose.ui:ui (org.jetbrains.compose.ui:ui-uikitx64): 0.0.0-master-dev673 (*)
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.1 (*)
\--- org.jetbrains.kotlinx:kotlinx-serialization-core (org.jetbrains.kotlinx:kotlinx-serialization-core-iosx64): 1.3.1 -> 1.3.2

(*) - dependencies omitted (listed previously)


```

**Comment by joreilly** [comment]
There's some discussion here, might be worth posting your issue in case anyone else has seen it https://kotlinlang.slack.com/archives/C0346LWVBJ4/p1651157631405989

**Pull request merged**
