### PR TITLE
smoke test bump to 1.4.20

### PR DESCRIPTION
**Pull request by dazza5000**

### CODE REVIEW

**Comment by joreilly** [comment]
Jetpack Compose seemingly doesn't work with 1.4.20 yet - see https://twitter.com/joreilly/status/1329395504309002240?s=20

**Comment by dazza5000** [comment]
It is building and rendering just fine on your project when testing on the emulator.

**Comment by dazza5000** [comment]
Screenshot from 2020-11-20 08-30-20

**Comment by dazza5000** [comment]
Screenshot from 2020-11-20 08-32-33

**Comment by dazza5000** [comment]
I'm wondering if that pr referenced in aosp is to just support using 1.4.2 in the compose project.

**Comment by dazza5000** [comment]
no rush! :)

**Comment by joreilly** [comment]
I think it might be more related to following which I only just noticed was still set to `1.4.0`

```
    composeOptions {
        kotlinCompilerVersion = "1.4.0"
        kotlinCompilerExtensionVersion = Versions.compose
    }
```

If I try changing that to `1.4.20` (along with other change you have here) then I get

```
IncompatibleClassChangeError: Found class org.jetbrains.kotlin.ir.declarations.IrClass, but interface was expected
```

**Comment by joreilly** [comment]
hmm, I changed that back to `1.4.0` and got same error (even after doing clean) (this is with the `val kotlin = "1.4.20"` change  still)

**Comment by dazza5000** [comment]
I had that same error you had - did you remove the android extensions plugin?

**Comment by joreilly** [comment]
Get a different error then `IllegalStateException: Backend Internal error: Exception during file facade code generation`

One other factor is that I'm still on AS 4.2 Canary 15 (haven't got option yet to update to 16...even if I check for updates...)

**Comment by dazza5000** [comment]
Interesting. Are you able to DL it directly? I am running 16 and maybe that is it.

**Comment by joreilly** [comment]
Closing this as this update came in as part of other changes

**Pull request closed without merging**
