### PR TITLE
Circular UI and card view.

### PR DESCRIPTION
**Pull request by percy-g2**

### CODE REVIEW

**Comment by joreilly** [comment]
Looks like Android instrumentation tests are failing with new layout

**Comment by joreilly** [comment]
I added same CardView UI just now to StartWars sample.....you can take look at update to tests there as well (extra `onChild` though might be better way of doing that) https://github.com/joreilly/StarWars/pull/110/files

**Comment by percy-g2** [comment]
10-4, let me check that and update you.

**Comment by percy-g2** [comment]
@joreilly fixed the test cases. Have a look

**Comment by percy-g2** [comment]
seems like your iOS pipe is broken and rest looks good.

**Pull request merged**
