### PR TITLE
Add collectAsStateWithLifecycle Flow extension

### PR DESCRIPTION
**Pull request by itsandreramon**
This PR adds a Flow extension to make lifecycle-aware Flow-collection more idiomatic when using Jetpack Compose as discussed here: https://twitter.com/manuelvicnt/status/1385530920384479233

### CODE REVIEW

**Comment by joreilly** [comment]
Nice! I'll merge shortly once CI workflow has completed

**Comment by itsandreramon** [comment]
Should I also add them for the other screens? I am unsure what to do with default values though, you have some collectAsState's without default values and AS cannot find listOf() on my machine. (stdlib broken again)

**Comment by joreilly** [comment]
The main need for this I think was for the ISS position updates.  This is one where it had kept polling while in background before those lifecycle related apis were added (at least when not using LiveData)

**Comment by joreilly** [comment]
@itsandreramon you can check this btw by filtering on "IssPosition" in logcat...it polls every 10s and you should see that stop when not on that screen or if you go in to background.

**Comment by joreilly** [comment]
There's a bit more background on this in https://johnoreilly.dev/posts/jetpack-compose-stateflow-livedata/

**Pull request merged**
