### PR TITLE
Use version catalogs and update mechanism

### PR DESCRIPTION
**Pull request by yschimke**
Before I migrate more than one module, wanted to check you are happy with the direction.

Question
- Default paths for deps e.g. libs.androidx.wear.compose.compose.navigation

It makes it simple to update update with

```
$ ./gradlew versionCatalogUpdate
```

### CODE REVIEW

**Comment by yschimke** [comment]
Result of running the update would be

```
@@ -1,17 +1,18 @@
 [versions]
 androidx-compose-ui = "1.1.0"
 androidx-glance = "1.0.0-alpha02"
-androidx-lifecycle = "2.4.0-rc01"
+androidx-lifecycle = "2.4.1"
 androidx-wear-compose = "1.0.0-alpha16"
-com-rickclephas-kmp = "0.11.1-new-mm"
+com-rickclephas-kmp = "0.11.2"
+com-squareup-okhttp3 = "4.9.3"
 com-squareup-sqldelight = "1.5.3"
-io-insert-koin = "3.1.4"
+io-insert-koin = "3.1.5"
 io-ktor = "2.0.0-beta-1"
 org-jetbrains-compose-web = "1.0.1"
 org-jetbrains-kotlin = "1.6.10"
 
 [libraries]
-androidx-activity-activity-compose = "androidx.activity:activity-compose:1.4.0-beta01"
+androidx-activity-activity-compose = "androidx.activity:activity-compose:1.4.0"
 androidx-compose-compiler = "androidx.compose.compiler:compiler:1.1.0"
 androidx-compose-foundation-foundation-layout = "androidx.compose.foundation:foundation-layout:1.1.0"
 androidx-compose-material = "androidx.compose.material:material:1.1.0"
@@ -26,25 +27,25 @@ androidx-glance-glance-wear-tiles = { module = "androidx.glance:glance-wear-tile
 androidx-lifecycle-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
 androidx-lifecycle-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
 androidx-navigation-navigation-compose = "androidx.navigation:navigation-compose:2.4.1"
-androidx-test-core = "androidx.test:core:1.3.0"
+androidx-test-core = "androidx.test:core:1.4.0"
 androidx-test-ext-junit = "androidx.test.ext:junit:1.1.3"
 androidx-wear-compose-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-wear-compose" }
 androidx-wear-compose-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-wear-compose" }
 androidx-wear-compose-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidx-wear-compose" }
-ch-qos-logback-logback-classic = "ch.qos.logback:logback-classic:1.2.3"
-co-touchlab-kermit = "co.touchlab:kermit:1.0.0"
+ch-qos-logback-logback-classic = "ch.qos.logback:logback-classic:1.2.10"
+co-touchlab-kermit = "co.touchlab:kermit:1.0.3"
 com-android-tools-build-gradle = "com.android.tools.build:gradle:7.1.1"
-com-expediagroup-graphql-kotlin-spring-server = "com.expediagroup:graphql-kotlin-spring-server:5.3.0"
+com-expediagroup-graphql-kotlin-spring-server = "com.expediagroup:graphql-kotlin-spring-server:5.3.2"
 com-github-ben-manes-gradle-versions-plugin = "com.github.ben-manes:gradle-versions-plugin:0.42.0"
 com-google-accompanist-accompanist-navigation-animation = "com.google.accompanist:accompanist-navigation-animation:0.23.0"
-com-google-android-material = "com.google.android.material:material:1.4.0"
+com-google-android-material = "com.google.android.material:material:1.5.0"
 com-google-cloud-tools-appengine-gradle-plugin = "com.google.cloud.tools:appengine-gradle-plugin:2.4.2"
 com-rickclephas-kmp-kmp-nativecoroutines-annotations = { module = "com.rickclephas.kmp:kmp-nativecoroutines-annotations", version.ref = "com-rickclephas-kmp" }
 com-rickclephas-kmp-kmp-nativecoroutines-compiler = { module = "com.rickclephas.kmp:kmp-nativecoroutines-compiler", version.ref = "com-rickclephas-kmp" }
 com-rickclephas-kmp-kmp-nativecoroutines-core = { module = "com.rickclephas.kmp:kmp-nativecoroutines-core", version.ref = "com-rickclephas-kmp" }
 com-rickclephas-kmp-kmp-nativecoroutines-gradle-plugin = { module = "com.rickclephas.kmp:kmp-nativecoroutines-gradle-plugin", version.ref = "com-rickclephas-kmp" }
-com-squareup-okhttp3-logging-interceptor = "com.squareup.okhttp3:logging-interceptor:4.9.2"
-com-squareup-okhttp3-okhttp = "com.squareup.okhttp3:okhttp:4.9.3"
+com-squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "com-squareup-okhttp3" }
+com-squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "com-squareup-okhttp3" }
 com-squareup-sqldelight-android-driver = { module = "com.squareup.sqldelight:android-driver", version.ref = "com-squareup-sqldelight" }
 com-squareup-sqldelight-coroutines-extensions = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "com-squareup-sqldelight" }
 com-squareup-sqldelight-gradle-plugin = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "com-squareup-sqldelight" }
@@ -53,7 +54,7 @@ com-squareup-sqldelight-native-driver-macosx64 = { module = "com.squareup.sqldel
 com-squareup-sqldelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "com-squareup-sqldelight" }
 com-squareup-sqldelight-sqlite-driver = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "com-squareup-sqldelight" }
 gradle-plugin-com-github-jengelman-gradle-plugins-shadow = "gradle.plugin.com.github.jengelman.gradle.plugins:shadow:7.0.0"
-io-coil-kt-coil-compose = "io.coil-kt:coil-compose:1.3.1"
+io-coil-kt-coil-compose = "io.coil-kt:coil-compose:1.4.0"
 io-insert-koin-koin-android = { module = "io.insert-koin:koin-android", version.ref = "io-insert-koin" }
 io-insert-koin-koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "io-insert-koin" }
 io-insert-koin-koin-core = { module = "io.insert-koin:koin-core", version.ref = "io-insert-koin" }
@@ -72,9 +73,9 @@ io-ktor-ktor-server-content-negotiation = { module = "io.ktor:ktor-server-conten
 io-ktor-ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "io-ktor" }
 io-ktor-ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "io-ktor" }
 io-ktor-ktor-websockets = { module = "io.ktor:ktor-websockets", version.ref = "io-ktor" }
-junit = "junit:junit:4.12"
+junit = "junit:junit:4.13.2"
 nl-littlerobots-vcu-plugin = "nl.littlerobots.vcu:plugin:0.3.0"
-org-jacoco-org-jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.3"
+org-jacoco-org-jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.7"
 org-jetbrains-compose-compiler = "org.jetbrains.compose.compiler:compiler:1.0.1"
 org-jetbrains-compose-desktop-desktop-jvm-macos-x64 = "org.jetbrains.compose.desktop:desktop-jvm-macos-x64:1.0.1"
 org-jetbrains-compose-runtime = "org.jetbrains.compose.runtime:runtime:1.0.1"
@@ -91,14 +92,14 @@ org-jetbrains-kotlin-kotlin-test-annotations-common = { module = "org.jetbrains.
 org-jetbrains-kotlin-kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "org-jetbrains-kotlin" }
 org-jetbrains-kotlinx-kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0"
 org-jetbrains-kotlinx-kotlinx-coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.0"
-org-jetbrains-kotlinx-kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.3.1"
+org-jetbrains-kotlinx-kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.3.2"
 org-jetbrains-kotlinx-kotlinx-serialization-core = "org.jetbrains.kotlinx:kotlinx-serialization-core:1.3.2"
-org-jetbrains-kotlinx-kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.1"
-org-jmailen-gradle-kotlinter-gradle = "org.jmailen.gradle:kotlinter-gradle:3.4.5"
-org-mockito-mockito-inline = "org.mockito:mockito-inline:3.11.2"
-org-osmdroid-osmdroid-android = "org.osmdroid:osmdroid-android:6.1.10"
-org-robolectric = "org.robolectric:robolectric:4.6.1"
-org-slf4j-slf4j-simple = "org.slf4j:slf4j-simple:1.7.30"
+org-jetbrains-kotlinx-kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2"
+org-jmailen-gradle-kotlinter-gradle = "org.jmailen.gradle:kotlinter-gradle:3.8.0"
+org-mockito-mockito-inline = "org.mockito:mockito-inline:4.3.1"
+org-osmdroid-osmdroid-android = "org.osmdroid:osmdroid-android:6.1.11"
+org-robolectric = "org.robolectric:robolectric:4.7.3"
+org-slf4j-slf4j-simple = "org.slf4j:slf4j-simple:1.7.36"
 
 [plugins]
 android = "android:7.1.1"
@@ -131,45 +132,45 @@ com-google-cloud-tools-appengine-flexible = "com.google.cloud.tools.appengine-fl
 com-google-cloud-tools-appengine-standard = "com.google.cloud.tools.appengine-standard:2.4.2"
 com-google-cloud-tools-source-context = "com.google.cloud.tools.source-context:2.4.2"
 com-gradle-plugin-publish = "com.gradle.plugin-publish:7.0.0"
-com-rickclephas-kmp-nativecoroutines = "com.rickclephas.kmp.nativecoroutines:0.11.1-new-mm"
+com-rickclephas-kmp-nativecoroutines = "com.rickclephas.kmp.nativecoroutines:0.11.2"
 com-squareup-sqldelight = "com.squareup.sqldelight:1.5.3"
-kotlin = "kotlin:1.6.10"
-kotlin-allopen = "kotlin-allopen:1.6.10"
-kotlin-android = "kotlin-android:1.6.10"
-kotlin-android-extensions = "kotlin-android-extensions:1.6.10"
-kotlin-dce-js = "kotlin-dce-js:1.6.10"
-kotlin-kapt = "kotlin-kapt:1.6.10"
-kotlin-multiplatform = "kotlin-multiplatform:1.6.10"
-kotlin-native-cocoapods = "kotlin-native-cocoapods:1.6.10"
-kotlin-native-performance = "kotlin-native-performance:1.6.10"
-kotlin-parcelize = "kotlin-parcelize:1.6.10"
-kotlin-platform-android = "kotlin-platform-android:1.6.10"
-kotlin-platform-common = "kotlin-platform-common:1.6.10"
-kotlin-platform-js = "kotlin-platform-js:1.6.10"
-kotlin-platform-jvm = "kotlin-platform-jvm:1.6.10"
-kotlin-scripting = "kotlin-scripting:1.6.10"
-kotlin-spring = "kotlin-spring:1.6.10"
-kotlin2js = "kotlin2js:1.6.10"
-kotlinx-serialization = "kotlinx-serialization:1.6.10"
+kotlin = "kotlin:1.6.20-M1"
+kotlin-allopen = "kotlin-allopen:1.6.20-M1"
+kotlin-android = "kotlin-android:1.6.20-M1"
+kotlin-android-extensions = "kotlin-android-extensions:1.6.20-M1"
+kotlin-dce-js = "kotlin-dce-js:1.6.20-M1"
+kotlin-kapt = "kotlin-kapt:1.6.20-M1"
+kotlin-multiplatform = "kotlin-multiplatform:1.6.20-M1"
+kotlin-native-cocoapods = "kotlin-native-cocoapods:1.6.20-M1"
+kotlin-native-performance = "kotlin-native-performance:1.6.20-M1"
+kotlin-parcelize = "kotlin-parcelize:1.6.20-M1"
+kotlin-platform-android = "kotlin-platform-android:1.6.20-M1"
+kotlin-platform-common = "kotlin-platform-common:1.6.20-M1"
+kotlin-platform-js = "kotlin-platform-js:1.6.20-M1"
+kotlin-platform-jvm = "kotlin-platform-jvm:1.6.20-M1"
+kotlin-scripting = "kotlin-scripting:1.6.20-M1"
+kotlin-spring = "kotlin-spring:1.6.20-M1"
+kotlin2js = "kotlin2js:1.6.20-M1"
+kotlinx-serialization = "kotlinx-serialization:1.6.20-M1"
 nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:0.3.0"
 org-jetbrains-compose = "org.jetbrains.compose:1.0.1"
-org-jetbrains-kotlin-android = "org.jetbrains.kotlin.android:1.6.10"
-org-jetbrains-kotlin-android-extensions = "org.jetbrains.kotlin.android.extensions:1.6.10"
-org-jetbrains-kotlin-js = "org.jetbrains.kotlin.js:1.6.10"
-org-jetbrains-kotlin-jvm = "org.jetbrains.kotlin.jvm:1.6.10"
-org-jetbrains-kotlin-kapt = "org.jetbrains.kotlin.kapt:1.6.10"
-org-jetbrains-kotlin-multiplatform = "org.jetbrains.kotlin.multiplatform:1.6.10"
-org-jetbrains-kotlin-multiplatform-pm20 = "org.jetbrains.kotlin.multiplatform.pm20:1.6.10"
-org-jetbrains-kotlin-native-cocoapods = "org.jetbrains.kotlin.native.cocoapods:1.6.10"
-org-jetbrains-kotlin-native-performance = "org.jetbrains.kotlin.native.performance:1.6.10"
-org-jetbrains-kotlin-platform-android = "org.jetbrains.kotlin.platform.android:1.6.10"
-org-jetbrains-kotlin-platform-common = "org.jetbrains.kotlin.platform.common:1.6.10"
-org-jetbrains-kotlin-platform-js = "org.jetbrains.kotlin.platform.js:1.6.10"
-org-jetbrains-kotlin-platform-jvm = "org.jetbrains.kotlin.platform.jvm:1.6.10"
-org-jetbrains-kotlin-plugin-allopen = "org.jetbrains.kotlin.plugin.allopen:1.6.10"
-org-jetbrains-kotlin-plugin-parcelize = "org.jetbrains.kotlin.plugin.parcelize:1.6.10"
-org-jetbrains-kotlin-plugin-scripting = "org.jetbrains.kotlin.plugin.scripting:1.6.10"
-org-jetbrains-kotlin-plugin-serialization = "org.jetbrains.kotlin.plugin.serialization:1.6.10"
-org-jetbrains-kotlin-plugin-spring = "org.jetbrains.kotlin.plugin.spring:1.6.10"
-org-jmailen-kotlinter = "org.jmailen.kotlinter:3.4.5"
-org-springframework-boot = "org.springframework.boot:2.5.6"
+org-jetbrains-kotlin-android = "org.jetbrains.kotlin.android:1.6.20-M1"
+org-jetbrains-kotlin-android-extensions = "org.jetbrains.kotlin.android.extensions:1.6.20-M1"
+org-jetbrains-kotlin-js = "org.jetbrains.kotlin.js:1.6.20-M1"
+org-jetbrains-kotlin-jvm = "org.jetbrains.kotlin.jvm:1.6.20-M1"
+org-jetbrains-kotlin-kapt = "org.jetbrains.kotlin.kapt:1.6.20-M1"
+org-jetbrains-kotlin-multiplatform = "org.jetbrains.kotlin.multiplatform:1.6.20-M1"
+org-jetbrains-kotlin-multiplatform-pm20 = "org.jetbrains.kotlin.multiplatform.pm20:1.6.20-M1"
+org-jetbrains-kotlin-native-cocoapods = "org.jetbrains.kotlin.native.cocoapods:1.6.20-M1"
+org-jetbrains-kotlin-native-performance = "org.jetbrains.kotlin.native.performance:1.6.20-M1"
+org-jetbrains-kotlin-platform-android = "org.jetbrains.kotlin.platform.android:1.6.20-M1"
+org-jetbrains-kotlin-platform-common = "org.jetbrains.kotlin.platform.common:1.6.20-M1"
+org-jetbrains-kotlin-platform-js = "org.jetbrains.kotlin.platform.js:1.6.20-M1"
+org-jetbrains-kotlin-platform-jvm = "org.jetbrains.kotlin.platform.jvm:1.6.20-M1"
+org-jetbrains-kotlin-plugin-allopen = "org.jetbrains.kotlin.plugin.allopen:1.6.20-M1"
+org-jetbrains-kotlin-plugin-parcelize = "org.jetbrains.kotlin.plugin.parcelize:1.6.20-M1"
+org-jetbrains-kotlin-plugin-scripting = "org.jetbrains.kotlin.plugin.scripting:1.6.20-M1"
+org-jetbrains-kotlin-plugin-serialization = "org.jetbrains.kotlin.plugin.serialization:1.6.20-M1"
+org-jetbrains-kotlin-plugin-spring = "org.jetbrains.kotlin.plugin.spring:1.6.20-M1"
+org-jmailen-kotlinter = "org.jmailen.kotlinter:3.8.0"
+org-springframework-boot = "org.springframework.boot:2.6.3"
```

**Comment by yschimke** [comment]
You can adjust rules to your liking in the root build.gradle.kts, but would presumably help you in the long term float the boats of all your projects.

**Comment by yschimke** [comment]
The initial catalog is created with

```
$ ./gradlew versionCatalogUpdate
```

**Comment by joreilly** [comment]
It does seem like this will become the standard approach.  Should this work with current stable version of AS?

**Comment by yschimke** [comment]
I'll check.

**Comment by yschimke** [comment]
Yep - I wanted your opinion on dependency naming and go ahead before doing the others.

**Comment by om-ha** [comment]
> It does seem like this will become the standard approach. Will this work with current stable version of AS?

I noticed the following:
- [version-catalog-update-plugin](https://github.com/littlerobots/version-catalog-update-plugin) requires `Gradle 7.2` or up as [mentioned here](https://github.com/littlerobots/version-catalog-update-plugin#getting-started).
- [gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugin) requires `Gradle 7.3.2` and up for constraints functionality as [mentioned here](https://github.com/ben-manes/gradle-versions-plugin#constraints).
- However PeopleInSpace currently uses `Gradle 7.1.1` as mentioned here: https://github.com/joreilly/PeopleInSpace/blob/6e93422efced492f478cce108bc65d1f0085e444/build.gradle.kts#L14

**Comment by yschimke** [comment]
This PR bumps to 7.4

**Comment by om-ha** [comment]
> This PR bumps to 7.4, you are pointing at the android plugin. Not gradle itself.
> 
> There is no 7.4 of the android plugin.

You're correct. This PR bumps Gradle from `7.2` to `7.4`.

```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip
```
Is now
```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip
```

[gradle/wrapper/gradle-wrapper.properties](https://github.com/joreilly/PeopleInSpace/pull/116/files#diff-40640fe1078ece83d7ea8fb67daacd77923a86d13447baf9769660b3b46f2ece)

**Comment by yschimke** [comment]
@joreilly From another project, there is discussion over using this version catalog + 3rd party update mechanism vs refreshVersions

https://jmfayard.github.io/refreshVersions/add-dependencies/

It has support for a lot of things including Wear Compose

https://github.com/jmfayard/refreshVersions/blob/16f3b1c5f03a9f3de2c4186bc32e0c6c68bd7039/plugins/dependencies/src/main/kotlin/dependencies/AndroidX.kt#L2727

**What is your view?**

**Comment by joreilly** [comment]
@yschimke I haven't looked in to that approach much but I'm just a little wary of pulling in 3rd party dependency for something like that and impact it might have in future on flexibility to change things independently.  Could perhaps be something that could be tried initially on one of the smaller samples to see how it works out.

**Comment by yschimke** [comment]
This is working really well, particularly with updates via renovate.  But I'll need to start a fresh and do all in one go.

See https://github.com/square/okhttp/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Frenovate

**Pull request closed without merging**
