### PR TITLE
Delay load on Wear, used cache data from DB.

### PR DESCRIPTION
**Pull request by yschimke**
For discussion, haven't tested on mobile yet.

Current logic on Android shows blank until the webservice request.  Instead use cached db results, and replace with updates afterwards.

### CODE REVIEW

**Comment by joreilly** [comment]
At least on Android and iOS the current code does drive UI from what's in the database so it should show what's cached in DB before web service request returns.  For that I think we should still have following in `PeopleInSpaceRepository`

```
    init {
        coroutineScope.launch {
            fetchAndStorePeople()
        }
    }
```

For Wear I had sort of bypassed this for some reason....think as initial test I had just hit endpoint directly,  But I think changes you made to `PersonList.kt` should work (with existing changes elsewhere).

**Comment by joreilly** [comment]
Actually, I don't think then that you should need following in `PersonList.kt` (with this being done from repository). So then shouldn't need change to `PeopleInSpaceRepositoryInterface` either.  I tested with that here and seems to work well.

```
    LaunchedEffect(true) {
        peopleInSpaceRepository.fetchAndStorePeople()
    }
```

**Comment by yschimke** [comment]
> At least on Android and iOS the current code does drive UI from what's in the database so it should show what's cached in DB before web service request returns. For that I think we should still have following in `PeopleInSpaceRepository`
> 
> ```
>     init {
>         coroutineScope.launch {
>             fetchAndStorePeople()
>         }
>     }
> ```
> 
> For Wear I had sort of bypassed this for some reason....think as initial test I had just hit endpoint directly, But I think changes you made to `PersonList.kt` should work (with mostly existing changes elsewhere).
> 
> Only other change needed I think then is to add `fetchAndStorePeople` to `PeopleInSpaceRepositoryInterface`

I think DI wise, I'd argue and try to convince you to not have that automatic.  Is there another way to schedule the actual work at startup, I'm conditioned to not put some mutative effects in a constructor.

**Comment by joreilly** [comment]
Yeah, that definitely makes sense... I'll look at another way to trigger it.

**Comment by yschimke** [comment]
BTW 
W/Kermit: Exception during fetchAndStorePeople: java.net.UnknownHostException: Unable to resolve host "people-in-space-proxy.ew.r.appspot.com": No address associated with hostname

**Pull request merged**
