### PR TITLE
Add option to enable / disable network logs

### LINKED ISSUE #18: Add option to disable ktor logs
For the CLI in #16 there should be an option to disable the ktor client logs - otherwise the CLI is filled up with network logs :)

I'm already working on a fix.

### PR DESCRIPTION
**Pull request by mreichelt**
- fix #18
- also make HttpClient and Json injectable

### CODE REVIEW

**Review by joreilly — APPROVED** [review]

**Comment by mreichelt** [comment]
Hey @joreilly - I'd love your input if this change would be beneficial for PeopleInSpace.

I simply wanted to add a global const `enableNetworkLogging`, but then I thought: well, the PeopleInSpaceApi currently is hard-coding the Json and HttpClient parts. Shouldn't those be injectable as well? This is a draft of that idea :)

Any thoughts on this?

**Comment by joreilly** [comment]
looks good!  will merge shortly (after ci build has completed)

**Comment by joreilly** [comment]
>> Edit: Haha, you approved this faster than I could add the comment - I'd still love to read your feedback though ;)

:-) Changes do look good....some of what was there has sort of evolved over time so nice to clean this up a bit (like actually pulling from dependency in main/test etc....and also injecting HttpClient)

**Comment by mreichelt** [comment]
Great - then I cleared the 'draft' label, and the PR is ready for merge :)

**Comment by joreilly** [comment]
Actually, one thing looking over this again....is handy running iOS etc app sometimes to see the ktor logs.  I can follow up with another PR for that (could pass flag down from iOS for example as you're doing for Android)

**Pull request merged**
